export const WORDS = {
  1: [
    { en: 'adjust', ko: '조정하다, 조절하다' },
    { en: 'anticipate', ko: '예상하다, 기대하다' },
    { en: 'anxiety', ko: '불안, 염려' },
    { en: 'anxious', ko: '불안해하는, 염려하는' },
    { en: 'applicable', ko: '적용되는, 해당되는' },
    { en: 'appointment', ko: '약속' },
    { en: 'arrangement', ko: '배치, 배열' },
    { en: 'as a result', ko: '결과적으로' },
    { en: 'at times', ko: '가끔은, 때로는' },
    { en: 'competition', ko: '대회, 시합' },
    { en: 'demanding', ko: '힘든, 부담이 큰' },
    { en: 'derive', ko: '끌어내다, 얻다' },
    { en: 'dimension', ko: '크기, 치수' },
    { en: 'elegant', ko: '우아한' },
    { en: 'embrace', ko: '받아들이다, 수용하다' },
    { en: 'emergency', ko: '비상, 비상사태' },
    { en: 'encouragement', ko: '격려' },
    { en: 'exhausted', ko: '기진맥진한, 탈진한' },
    { en: 'figure out', ko: '이해하다, 생각해 내다' },
    { en: 'flexible', ko: '유연한, 융통성 있는' },
    { en: 'go blank', ko: '(마음이) 텅 비다' },
    { en: 'hospitalize', ko: '입원시키다' },
    { en: 'in advance', ko: '미리, 전부터' },
    { en: 'incorporate', ko: '포함하다' },
    { en: 'investigate', ko: '조사하다, 수사하다' },
    { en: 'journey', ko: '여행, 여정' },
    { en: 'lead to', ko: '~로 이어지다' },
    { en: 'look forward to', ko: '~을 기대하다' },
    { en: 'mentor', ko: '멘토, 유경험자 선배' },
    { en: 'motive', ko: '동기, 이유' },
    { en: 'negotiate', ko: '협상하다, 교섭하다' },
    { en: 'novelist', ko: '소설가' },
    { en: 'opportunity', ko: '기회' },
    { en: 'participate in', ko: '~에 참가하다, 참여하다' },
    { en: 'passionate', ko: '열정적인, 열렬한' },
    { en: 'profiler', ko: '범죄 심리 분석관' },
    { en: 'put on', ko: '상연하다' },
    { en: 'rehearsal', ko: '리허설, 예행연습' },
    { en: 'relieve', ko: '완화하다' },
    { en: 'rhythm', ko: '리듬, 규칙적 변화' },
    { en: 'sensation', ko: '선풍, 돌풍' },
    { en: 'strength', ko: '힘, 내구력' },
    { en: 'struggle', ko: '애쓰다, 힘겹게 싸우다' },
    { en: 'subscriber', ko: '구독자' },
    { en: 'suitable', ko: '적합한, 적절한' },
    { en: 'take on', ko: '떠맡다' },
    { en: 'thoroughly', ko: '철저히, 철두철미하게' },
    { en: 'undergo', ko: '겪다, 경험하다' },
    { en: 'unforgettable', ko: '잊지 못할, 잊을 수 없는' },
    { en: 'witness', ko: '목격자, 증인' },
  ],
  2: [
    { en: 'acknowledgement', ko: '승인, 시인' },
    { en: 'astonish', ko: '깜짝 놀라게 하다' },
    { en: 'bendable', ko: '구부릴 수 있는' },
    { en: 'boredom', ko: '지루함, 따분함' },
    { en: 'captivate', ko: '마음을 사로잡다, 매혹하다' },
    { en: 'come across', ko: '우연히 마주치다, 발견하다' },
    { en: 'come up with', ko: '생각해 내다, 떠올리다' },
    { en: 'committee', ko: '위원회' },
    { en: 'conference', ko: '회의, 회담' },
    { en: 'contrary', ko: '반대되는, 다른' },
    { en: 'destructive', ko: '파괴적인' },
    { en: 'dishonesty', ko: '부정행위, 사기' },
    { en: 'dispute', ko: '반박하다, 이의를 제기하다' },
    { en: 'dissatisfaction', ko: '불만' },
    { en: 'donate', ko: '기부하다, 기증하다' },
    { en: 'efficient', ko: '효율적인, 능률적인' },
    { en: 'elderly', ko: '연세가 드신' },
    { en: 'embassy', ko: '대사관' },
    { en: 'excessive', ko: '지나친, 과도한' },
    { en: 'extraordinary', ko: '비범한, 대단한' },
    { en: 'foldable', ko: '접을 수 있는, 접히는' },
    { en: 'glitter', ko: '반짝반짝 빛나다' },
    { en: 'go through', ko: '겪다, 경험하다' },
    { en: 'hint at', ko: '~을 암시하다' },
    { en: 'hostile', ko: '적대적인' },
    { en: 'immediately', ko: '즉시, 즉각' },
    { en: 'intermediate', ko: '중간의, 중급의' },
    { en: 'mechanical', ko: '기계로 작동되는' },
    { en: 'miss out on', ko: '~을 놓치다' },
    { en: 'nonetheless', ko: '그렇기는 하지만' },
    { en: 'on duty', ko: '근무 중, 일하고 있는' },
    { en: 'outline', ko: '윤곽' },
    { en: 'pathway', ko: '길' },
    { en: 'perception', ko: '지각, 자각' },
    { en: 'permanent', ko: '영구적인, 영속적인' },
    { en: 'perspective', ko: '관점, 시각' },
    { en: 'pioneer', ko: '개척자, 선구자' },
    { en: 'product', ko: '상품, 제품' },
    { en: 'prominent', ko: '두드러진, 현저한' },
    { en: 'questionnaire', ko: '설문지' },
    { en: 'result in', ko: '~을 야기하다, 낳다' },
    { en: 'revolutionize', ko: '혁신을 일으키다' },
    { en: 'ripe', ko: '익은, 숙성한' },
    { en: 'sprout', ko: '새싹이 나다' },
    { en: 'sum up', ko: '요약하다' },
    { en: 'ultimately', ko: '결국, 궁극적으로' },
    { en: 'unconventional', ko: '색다른, 독특한' },
    { en: 'unified', ko: '통일된, 통합된' },
    { en: 'unprecedented', ko: '전례 없는, 미증유의' },
    { en: 'vineyard', ko: '포도밭, 포도원' },
  ],
}